<%@ page language="java" import="java.util.*" pageEncoding="utf-8"%>

<div id="footer-link">
    关于川润海 | 诚聘英才 | 法律声明 | 友情链接 | 帮助中心 | 网站地图 | 意见反馈 | 联系我们 <script src="http://s22.cnzz.com/stat.php?id=4139654&web_id=4139654&show=pic" language="JavaScript"></script>
  </div>
   
 <p>地　址：苏州市吴中区东吴南路388号吴中商城大厦1707室</p>
  <p>电　话：0512-66593679 传　真：0512-66593679</p>
  <p>Copyright © 2012 天时软件工作室 版权所有 </p>
 
 