<%@ page language="java" import="java.util.*" pageEncoding="utf-8"%>
<img src="${imgPath}/portal/logo.png"/>
<div id="nav">
    <ul id="pr">
      <li id="home" ><a href="/PRS/sys/portal_welcome" target="_self"><span>首页</span></a> </li>
      <li id="news" ><a href="/PRS/sys/portal_welcome" target="_self"><span>新闻中心</span></a></li>
      <li id="comp"><a href="/PRS/sys/portal_company" target="_self"><span>公司简介</span></a></li>
      <li id="busi"><a href="/info/main/" target="_self"><span>业务范围</span></a></li>
      <li id="recom"><a href="/info/main/" target="_self"><span>人才自荐</span></a></li>
      <li id="cont"><a href="/info/main/" target="_self"><span>联系我们</span></a></li>
    </ul>
</div>