<%@ page language="java" import="java.util.*" pageEncoding="utf-8"%>
<div class="cont">  
    <ul id="user" style="float:left">
      <li id="welcome_logon_span">&nbsp;欢迎来到川润海</li> 
      <li id="front_page" style="display: inline;">
        <a rel="nofollow" href="/PRS/sys/manage_LoginPage">登录</a> |
      </li>
      <li id="favo_page" style="display: inline;">
        <a rel="nofollow" href="/PRS/sys/manage_RegistionPage">注册</a> |
      </li>    
    </ul>     
  </div>